import FWCore.ParameterSet.Config as cms

process = cms.Process("TEST")

process.inputTree = cms.PSet(
  nameTree = cms.string("ntupleEcalAlignment/myTree"),
#  selection = cms.string("(eleFBrem<0.8&&eleCharge>0)"),
  selection = cms.string("1"),
  traslationX = cms.bool(True),
  traslationY = cms.bool(True),
  traslationZ = cms.bool(True),
  rotationPhi   = cms.bool(False),
  rotationTheta = cms.bool(False),
  rotationPsi   = cms.bool(False),
  inputFiles    = cms.vstring(
         '/tmp/amassiro/EcalAlignment/EcalAlignmentJoin.root'
              
         #'rfio:/castor/cern.ch/user/a/amassiro/EcalAlignment/WZEG_RAWRECO_NoAlign/EcalAlignment_10_1_KAK.root',
         #'rfio:/castor/cern.ch/user/a/amassiro/EcalAlignment/WZEG_RAWRECO_NoAlign/EcalAlignment_11_1_wR7.root',
         #'rfio:/castor/cern.ch/user/a/amassiro/EcalAlignment/WZEG_RAWRECO_NoAlign/EcalAlignment_12_1_0LU.root',
         #'rfio:/castor/cern.ch/user/a/amassiro/EcalAlignment/WZEG_RAWRECO_NoAlign/EcalAlignment_13_1_S3K.root',
         #'rfio:/castor/cern.ch/user/a/amassiro/EcalAlignment/WZEG_RAWRECO_NoAlign/EcalAlignment_14_1_aHN.root',
         #'rfio:/castor/cern.ch/user/a/amassiro/EcalAlignment/WZEG_RAWRECO_NoAlign/EcalAlignment_15_1_t9R.root',
         #'rfio:/castor/cern.ch/user/a/amassiro/EcalAlignment/WZEG_RAWRECO_NoAlign/EcalAlignment_16_1_jXI.root',
         #'rfio:/castor/cern.ch/user/a/amassiro/EcalAlignment/WZEG_RAWRECO_NoAlign/EcalAlignment_17_1_0Gh.root',
         #'rfio:/castor/cern.ch/user/a/amassiro/EcalAlignment/WZEG_RAWRECO_NoAlign/EcalAlignment_18_1_FjD.root',
         #'rfio:/castor/cern.ch/user/a/amassiro/EcalAlignment/WZEG_RAWRECO_NoAlign/EcalAlignment_19_1_B8y.root',
         #'rfio:/castor/cern.ch/user/a/amassiro/EcalAlignment/WZEG_RAWRECO_NoAlign/EcalAlignment_1_1_WNK.root',
         #'rfio:/castor/cern.ch/user/a/amassiro/EcalAlignment/WZEG_RAWRECO_NoAlign/EcalAlignment_20_1_PMy.root',
         #'rfio:/castor/cern.ch/user/a/amassiro/EcalAlignment/WZEG_RAWRECO_NoAlign/EcalAlignment_21_1_UYU.root',
         #'rfio:/castor/cern.ch/user/a/amassiro/EcalAlignment/WZEG_RAWRECO_NoAlign/EcalAlignment_22_1_gP7.root',
         #'rfio:/castor/cern.ch/user/a/amassiro/EcalAlignment/WZEG_RAWRECO_NoAlign/EcalAlignment_23_1_5PQ.root',
         #'rfio:/castor/cern.ch/user/a/amassiro/EcalAlignment/WZEG_RAWRECO_NoAlign/EcalAlignment_24_1_Jfc.root',
         #'rfio:/castor/cern.ch/user/a/amassiro/EcalAlignment/WZEG_RAWRECO_NoAlign/EcalAlignment_25_1_6RC.root',
         #'rfio:/castor/cern.ch/user/a/amassiro/EcalAlignment/WZEG_RAWRECO_NoAlign/EcalAlignment_26_1_jh4.root',
         #'rfio:/castor/cern.ch/user/a/amassiro/EcalAlignment/WZEG_RAWRECO_NoAlign/EcalAlignment_27_1_OBT.root',
         #'rfio:/castor/cern.ch/user/a/amassiro/EcalAlignment/WZEG_RAWRECO_NoAlign/EcalAlignment_28_1_wBV.root',
         #'rfio:/castor/cern.ch/user/a/amassiro/EcalAlignment/WZEG_RAWRECO_NoAlign/EcalAlignment_29_1_B75.root',
         #'rfio:/castor/cern.ch/user/a/amassiro/EcalAlignment/WZEG_RAWRECO_NoAlign/EcalAlignment_2_1_TW6.root',
         #'rfio:/castor/cern.ch/user/a/amassiro/EcalAlignment/WZEG_RAWRECO_NoAlign/EcalAlignment_30_1_nnW.root',
         #'rfio:/castor/cern.ch/user/a/amassiro/EcalAlignment/WZEG_RAWRECO_NoAlign/EcalAlignment_31_1_RTC.root',
         #'rfio:/castor/cern.ch/user/a/amassiro/EcalAlignment/WZEG_RAWRECO_NoAlign/EcalAlignment_32_1_zKY.root',
         #'rfio:/castor/cern.ch/user/a/amassiro/EcalAlignment/WZEG_RAWRECO_NoAlign/EcalAlignment_33_1_FBX.root',
         #'rfio:/castor/cern.ch/user/a/amassiro/EcalAlignment/WZEG_RAWRECO_NoAlign/EcalAlignment_34_1_36a.root',
         #'rfio:/castor/cern.ch/user/a/amassiro/EcalAlignment/WZEG_RAWRECO_NoAlign/EcalAlignment_35_1_A74.root',
         #'rfio:/castor/cern.ch/user/a/amassiro/EcalAlignment/WZEG_RAWRECO_NoAlign/EcalAlignment_36_1_2AI.root',
         #'rfio:/castor/cern.ch/user/a/amassiro/EcalAlignment/WZEG_RAWRECO_NoAlign/EcalAlignment_37_1_wSq.root',
         #'rfio:/castor/cern.ch/user/a/amassiro/EcalAlignment/WZEG_RAWRECO_NoAlign/EcalAlignment_38_1_VWS.root',
         #'rfio:/castor/cern.ch/user/a/amassiro/EcalAlignment/WZEG_RAWRECO_NoAlign/EcalAlignment_39_1_wH2.root',
         #'rfio:/castor/cern.ch/user/a/amassiro/EcalAlignment/WZEG_RAWRECO_NoAlign/EcalAlignment_3_1_gv0.root',
         #'rfio:/castor/cern.ch/user/a/amassiro/EcalAlignment/WZEG_RAWRECO_NoAlign/EcalAlignment_40_1_WD2.root',
         #'rfio:/castor/cern.ch/user/a/amassiro/EcalAlignment/WZEG_RAWRECO_NoAlign/EcalAlignment_41_1_cpd.root',
         #'rfio:/castor/cern.ch/user/a/amassiro/EcalAlignment/WZEG_RAWRECO_NoAlign/EcalAlignment_4_1_FgG.root',
         #'rfio:/castor/cern.ch/user/a/amassiro/EcalAlignment/WZEG_RAWRECO_NoAlign/EcalAlignment_5_1_5WT.root',
         #'rfio:/castor/cern.ch/user/a/amassiro/EcalAlignment/WZEG_RAWRECO_NoAlign/EcalAlignment_6_1_p4s.root',
         #'rfio:/castor/cern.ch/user/a/amassiro/EcalAlignment/WZEG_RAWRECO_NoAlign/EcalAlignment_7_1_LiF.root',
         #'rfio:/castor/cern.ch/user/a/amassiro/EcalAlignment/WZEG_RAWRECO_NoAlign/EcalAlignment_8_1_RF4.root',
         #'rfio:/castor/cern.ch/user/a/amassiro/EcalAlignment/WZEG_RAWRECO_NoAlign/EcalAlignment_9_1_keB.root',
     
         #'rfio:/castor/cern.ch/user/a/amassiro/EcalAlignment/Filter_RAWRECO_NoAlign/EcalAlignment_10_1_Rys.root',
         #'rfio:/castor/cern.ch/user/a/amassiro/EcalAlignment/Filter_RAWRECO_NoAlign/EcalAlignment_11_1_rug.root',
         #'rfio:/castor/cern.ch/user/a/amassiro/EcalAlignment/Filter_RAWRECO_NoAlign/EcalAlignment_12_1_7WK.root',
         #'rfio:/castor/cern.ch/user/a/amassiro/EcalAlignment/Filter_RAWRECO_NoAlign/EcalAlignment_13_1_ZJx.root',
         #'rfio:/castor/cern.ch/user/a/amassiro/EcalAlignment/Filter_RAWRECO_NoAlign/EcalAlignment_14_1_xQg.root',
         #'rfio:/castor/cern.ch/user/a/amassiro/EcalAlignment/Filter_RAWRECO_NoAlign/EcalAlignment_15_1_zNo.root',
         #'rfio:/castor/cern.ch/user/a/amassiro/EcalAlignment/Filter_RAWRECO_NoAlign/EcalAlignment_16_1_quQ.root',
         #'rfio:/castor/cern.ch/user/a/amassiro/EcalAlignment/Filter_RAWRECO_NoAlign/EcalAlignment_17_1_t8U.root',
         #'rfio:/castor/cern.ch/user/a/amassiro/EcalAlignment/Filter_RAWRECO_NoAlign/EcalAlignment_18_1_vdV.root',
         #'rfio:/castor/cern.ch/user/a/amassiro/EcalAlignment/Filter_RAWRECO_NoAlign/EcalAlignment_19_1_sHg.root',
         #'rfio:/castor/cern.ch/user/a/amassiro/EcalAlignment/Filter_RAWRECO_NoAlign/EcalAlignment_1_1_mQm.root',
         #'rfio:/castor/cern.ch/user/a/amassiro/EcalAlignment/Filter_RAWRECO_NoAlign/EcalAlignment_20_1_fTH.root',
         #'rfio:/castor/cern.ch/user/a/amassiro/EcalAlignment/Filter_RAWRECO_NoAlign/EcalAlignment_21_1_an9.root',
         #'rfio:/castor/cern.ch/user/a/amassiro/EcalAlignment/Filter_RAWRECO_NoAlign/EcalAlignment_22_1_YAQ.root',
         #'rfio:/castor/cern.ch/user/a/amassiro/EcalAlignment/Filter_RAWRECO_NoAlign/EcalAlignment_23_1_gaA.root',
         #'rfio:/castor/cern.ch/user/a/amassiro/EcalAlignment/Filter_RAWRECO_NoAlign/EcalAlignment_24_1_BOU.root',
         #'rfio:/castor/cern.ch/user/a/amassiro/EcalAlignment/Filter_RAWRECO_NoAlign/EcalAlignment_25_1_wBk.root',
         #'rfio:/castor/cern.ch/user/a/amassiro/EcalAlignment/Filter_RAWRECO_NoAlign/EcalAlignment_26_1_jWH.root',
         #'rfio:/castor/cern.ch/user/a/amassiro/EcalAlignment/Filter_RAWRECO_NoAlign/EcalAlignment_27_1_VNt.root',
         #'rfio:/castor/cern.ch/user/a/amassiro/EcalAlignment/Filter_RAWRECO_NoAlign/EcalAlignment_28_1_Y28.root',
         #'rfio:/castor/cern.ch/user/a/amassiro/EcalAlignment/Filter_RAWRECO_NoAlign/EcalAlignment_2_1_056.root',
         #'rfio:/castor/cern.ch/user/a/amassiro/EcalAlignment/Filter_RAWRECO_NoAlign/EcalAlignment_30_1_0kp.root',
         #'rfio:/castor/cern.ch/user/a/amassiro/EcalAlignment/Filter_RAWRECO_NoAlign/EcalAlignment_3_1_6Lq.root',
         #'rfio:/castor/cern.ch/user/a/amassiro/EcalAlignment/Filter_RAWRECO_NoAlign/EcalAlignment_4_1_MOx.root',
         #'rfio:/castor/cern.ch/user/a/amassiro/EcalAlignment/Filter_RAWRECO_NoAlign/EcalAlignment_5_1_p5I.root',
         #'rfio:/castor/cern.ch/user/a/amassiro/EcalAlignment/Filter_RAWRECO_NoAlign/EcalAlignment_6_1_5kw.root',
         #'rfio:/castor/cern.ch/user/a/amassiro/EcalAlignment/Filter_RAWRECO_NoAlign/EcalAlignment_7_1_5dI.root',
         #'rfio:/castor/cern.ch/user/a/amassiro/EcalAlignment/Filter_RAWRECO_NoAlign/EcalAlignment_8_1_9qr.root',
         #'rfio:/castor/cern.ch/user/a/amassiro/EcalAlignment/Filter_RAWRECO_NoAlign/EcalAlignment_9_1_TpQ.root'
#        'EcalAlignment.root'
    )
)


process.outputTree = cms.PSet(
 #outputFile = cms.string("myEBAlignment_2010.txt"),
 outputFile = cms.string("myEEAlignment_2010.txt"),
)
